services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    volumes:
      - .:/myapp
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rails_app
    depends_on:
      - 'db'
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rails_app
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  bundle_cache: